### PR TITLE
Removes erroneous phinx environment connections

### PR DESCRIPTION
**Pull request by paul-crashley**
You don't need develop, production, etc... connections when using DotEnv. That's taken care of by DotEnv itself.

### CODE REVIEW

**Comment by rosenstrauch** [comment]
thank you! you are of course correct and this will help getting to a [safe and sane use of environment variables](#53 ). am running this through our pipeline.

I will also change the default github branch to develop to ensure that is used as a base branch for pullrequests.

**Comment by Nebel54** [comment]
Liebe Kunden, Freunde und Spammer,
wir sind bis 11.12.2017 nicht im Büro und können Ihre Anfragen daher nicht sofort beantworten. 

Liebe Grüße
Oliver Köhler

**Comment by rosenstrauch** [comment]
to be able to merge this without breaking our builds the https://github.com/acolono/opencounter_api/blob/develop/app/phinx.php will also need to be adjusted accordingly

**Comment by paul-crashley** [comment]
I've changed the base to develop, which can then be merged in to master. If that doesn't work properly, let me know and I'll create a new merge request.

**Pull request merged**
